package com.example.ui

object Localization {

    data class DemoChipData(
        val label: String,
        val phrase: String
    )

    val supportedLanguages = listOf(
        "English", "Hindi", "Hinglish", "Tamil", "Telugu", "Bengali", "Kannada", "Marathi"
    )

    private val translations = mapOf(
        "English" to mapOf(
            "APP_NAME" to "VoiceOPS AI",
            "SUBTITLE" to "Informal Economy Business OS",
            "AI_ACTIVE" to "AI ACTIVE",
            "TOTAL_SALES" to "TOTAL SALES",
            "UDHAAR_DUE" to "UDHAAR (DUE)",
            "EXPENSES" to "EXPENSES",
            "MIC_TAP_PROMPT" to "TAP MIC & SPEAK OPERATIONAL DETAILS",
            "TAP_TO_SPEAK_LABEL" to "Tap to Speak Hindi/English/Hinglish",
            "TRANSLATING" to "VoiceNLP Translating audio...",
            "DEMO_CHIPS_HEADER" to "DEMO CHIPS: TAP TO SIMULATE VOICE SPEECHES",
            "LEDGER_STREAM_TAB" to "📊 Ledger Stream",
            "MANDI_PRICES_TAB" to "🌾 Mandi Prices",
            "VOICE_CREDIT_TAB" to "💳 Voice-Credit",
            "LEDGER_EMPTY_TITLE" to "Operational Ledger Empty",
            "LEDGER_EMPTY_DESC" to "No log written. Speak with mic or load demo ledger records below to try out automatic visual summaries instantly.",
            "LOAD_SAMPLE_BUTTON" to "Load Sample Dataset",
            "ACTIVE_RECORDS" to "ACTIVE RECORDS WRITTEN",
            "CLEAR_ALL" to "Clear All Records",
            "LIVE_COMMODITY_INDICATOR" to "LIVE REGIONAL COMMODITY INDICATOR",
            "CREDIT_ELIGIBILITY_TITLE" to "VOICE-VERIFIED BUSINESS ELIGIBILITY PROFILE",
            "CREDIT_SCORE_TITLE" to "VOICE LEDGER CREDIT CASHFLOW SCORE",
            "EXCELLENT" to "EXCELLENT",
            "GOOD_TIER" to "GOOD TIER",
            "NEEDS_MORE_DATA" to "NEEDS MORE DATA",
            "CRYPTO_VOLUME" to "Cryptographic Voice ledger volume:",
            "PARTNER_INTEGRATION_TITLE" to "Bank / NBFC Partner Integration",
            "APPLY_LOAN_BUTTON" to "APPLY TO FORWARD COLLATERAL-FREE LOAN",
            "EXPLAINED_OUT_LOUD" to "EXPLAINED OUT LOUD IN LOCAL ACCENT:",
            "DONE_BUTTON" to "Done / Thik Hai",
            "VOICE_TRANSLATION_TITLE" to "VoiceOPS Translation",
            "REGION_DEFAULT_BANNER" to "Location-Adapted Default Setup:",
            "ITEM" to "Item extracted",
            "CAT" to "Transaction Category",
            "QTY" to "Quantity standard",
            "RATE" to "Rate standard",
            "TOTAL" to "Total calculated",
            "DEBT" to "Debt Party"
        ),
        "Hindi" to mapOf(
            "APP_NAME" to "वॉयस-ओपीएस एआई",
            "SUBTITLE" to "लघु व्यवसायों का डिजिटल बहीखाता",
            "AI_ACTIVE" to "एआई सक्रिय है",
            "TOTAL_SALES" to "कुल बिक्री",
            "UDHAAR_DUE" to "बाकी उधार राशि",
            "EXPENSES" to "कुल खर्चे",
            "MIC_TAP_PROMPT" to "माइक छुएं और बहीखाता विवरण बोलें",
            "TAP_TO_SPEAK_LABEL" to "बोलने के लिए दबाएं (हिन्दी/अंग्रेज़ी)",
            "TRANSLATING" to "एआई आपकी आवाज समझ रहा है...",
            "DEMO_CHIPS_HEADER" to "डेमो बटन: परीक्षण के लिए सीधे दबाएं",
            "LEDGER_STREAM_TAB" to "📊 बहीखाता इतिहास",
            "MANDI_PRICES_TAB" to "🌾 ताजा मंडी भाव",
            "VOICE_CREDIT_TAB" to "💳 वॉयस-क्रेडिट लोन",
            "LEDGER_EMPTY_TITLE" to "बहीखाता अभी खाली है",
            "LEDGER_EMPTY_DESC" to "कोई रिकॉर्ड नहीं मिला। माइक का उपयोग करके बोलें या नीचे दिए गए बटन पर क्लिक करके डेमो रिकॉर्ड लोड करें।",
            "LOAD_SAMPLE_BUTTON" to "डेमो जानकारी लोड करें",
            "ACTIVE_RECORDS" to "सक्रिय व्यापार रिकॉर्ड लिखे गए",
            "CLEAR_ALL" to "सभी रिकॉर्ड साफ करें",
            "LIVE_COMMODITY_INDICATOR" to "ताजा क्षेत्रीय फसल मंडी दरें",
            "CREDIT_ELIGIBILITY_TITLE" to "आवाज-सत्यापित व्यापार ऋण प्रोफाइल",
            "CREDIT_SCORE_TITLE" to "भाषण बहीखाता नकदी प्रवाह स्कोर",
            "EXCELLENT" to "उत्कृष्ट रेटिंग",
            "GOOD_TIER" to "अच्छा स्तर",
            "NEEDS_MORE_DATA" to "अधिक डेटा की आवश्यकता है",
            "CRYPTO_VOLUME" to "सत्यापित वॉयस बहीखाता कुल लेन-देन:",
            "PARTNER_INTEGRATION_TITLE" to "सहयोगी बैंक एवं ग्रामीण फाइनेंस",
            "APPLY_LOAN_BUTTON" to "बिना किसी गारंटी के ऋण आवेदन करें",
            "EXPLAINED_OUT_LOUD" to "स्थानीय उच्चारण में स्पष्टीकरण:",
            "DONE_BUTTON" to "ठीक है / पूरा हुआ",
            "VOICE_TRANSLATION_TITLE" to "वॉयस अनुवाद परिणाम",
            "REGION_DEFAULT_BANNER" to "स्थान-अनुकूलित डिफॉल्ट सेटअप:",
            "ITEM" to "उत्पाद का नाम",
            "CAT" to "लेन-देन श्रेणी",
            "QTY" to "मात्रा विवरण",
            "RATE" to "प्रति यूनिट दर",
            "TOTAL" to "कुल गणना राशि",
            "DEBT" to "उधार लेने वाला"
        ),
        "Hinglish" to mapOf(
            "APP_NAME" to "VoiceOPS AI",
            "SUBTITLE" to "Sadharan Vyapar Ka Digital Ledger OS",
            "AI_ACTIVE" to "AI ACTIVE HAI",
            "TOTAL_SALES" to "TOTAL SALES (BIKRI)",
            "UDHAAR_DUE" to "UDHAAR (BAAKI)",
            "EXPENSES" to "KHARACH (EXPENSES)",
            "MIC_TAP_PROMPT" to "TAP MIC & APNI BOLI MEIN DETAILS BOLEIN",
            "TAP_TO_SPEAK_LABEL" to "Tap to Speak Hindi/English/Hinglish",
            "TRANSLATING" to "Voice NLP translate kar raha hai...",
            "DEMO_CHIPS_HEADER" to "DEMO CHIPS: TEST KARNE KE LIYE TAP KAREIN",
            "LEDGER_STREAM_TAB" to "📊 Ledger History",
            "MANDI_PRICES_TAB" to "🌾 Mandi Bhav",
            "VOICE_CREDIT_TAB" to "💳 Voice Credit Score",
            "LEDGER_EMPTY_TITLE" to "Ledger Khali Hai",
            "LEDGER_EMPTY_DESC" to "Koi record nahi mila. Mic dabakar boleya ya fir sample records ko load karke turant check karein.",
            "LOAD_SAMPLE_BUTTON" to "Sample Records Load Karein",
            "ACTIVE_RECORDS" to "ACTIVE RECORDS LIKHE GAYE",
            "CLEAR_ALL" to "Saare records udaayein",
            "LIVE_COMMODITY_INDICATOR" to "LIVE APNE REGION KA MANDI RATE",
            "CREDIT_ELIGIBILITY_TITLE" to "VOICE-VERIFIED BUSINESS ELIGIBILITY",
            "CREDIT_SCORE_TITLE" to "VOICE LEDGER SE CREDIT LOAN SCORE",
            "EXCELLENT" to "EXCELLENT STATUS",
            "GOOD_TIER" to "GOOD SCORE TIER",
            "NEEDS_MORE_DATA" to "KUCH OR RECORDS CHAHIYE",
            "CRYPTO_VOLUME" to "Total Voice Ledger Volume recorded:",
            "PARTNER_INTEGRATION_TITLE" to "Rural NBFC / Bank Partner Linkage",
            "APPLY_LOAN_BUTTON" to "COLLATERAL-FREE LOAN KE LIYE APPLY KAREIN",
            "EXPLAINED_OUT_LOUD" to "Mera voice assistant bola:",
            "DONE_BUTTON" to "Thik Hai / Done",
            "VOICE_TRANSLATION_TITLE" to "Voice Translation",
            "REGION_DEFAULT_BANNER" to "Location-Adapted Default Setup:",
            "ITEM" to "Khaas Saman",
            "CAT" to "Transaction Category",
            "QTY" to "Total Quantity",
            "RATE" to "Price per Unit",
            "TOTAL" to "Total Amount",
            "DEBT" to "Udhaar Party"
        ),
        "Tamil" to mapOf(
            "APP_NAME" to "வாய்ஸ்-ஓபிஎஸ் ஏஐ",
            "SUBTITLE" to "சிறு வணிகர்களுக்கான டிஜிட்டல் பேரேடு",
            "AI_ACTIVE" to "ஏஐ செயலில் உள்ளது",
            "TOTAL_SALES" to "மொத்த விற்பனை",
            "UDHAAR_DUE" to "பாக்கிக் கடன்",
            "EXPENSES" to "மொத்த செலவுகள்",
            "MIC_TAP_PROMPT" to "மைக்கைத் தட்டி வணிக விவரங்களைப் பேசவும்",
            "TAP_TO_SPEAK_LABEL" to "பேச தட்டவும் (தமிழ்/ஆங்கிலம்)",
            "TRANSLATING" to "குரல் மொழிபெயர்க்கப்படுகிறது...",
            "DEMO_CHIPS_HEADER" to "டெமோ சில்லுகள்: பேசும் குரலை உருவகப்படுத்த தட்டவும்",
            "LEDGER_STREAM_TAB" to "📊 பேரேடு வரலாறு",
            "MANDI_PRICES_TAB" to "🌾 மண்டி நிலவரம்",
            "VOICE_CREDIT_TAB" to "💳 குரல் கடன் தகுதி",
            "LEDGER_EMPTY_TITLE" to "பேரேடு காலியாக உள்ளது",
            "LEDGER_EMPTY_DESC" to "பதிவுகள் எதுவும் இல்லை. மைக்கில் பேசவும் அல்லது டெமோ பதிவுகளை ஏற்றவும்.",
            "LOAD_SAMPLE_BUTTON" to "மாதிரி தரவை ஏற்றவும்",
            "ACTIVE_RECORDS" to "பதிவு செய்யப்பட்ட செயலில் உள்ள பதிவுகள்",
            "CLEAR_ALL" to "பதிவுகளை நீக்கு",
            "LIVE_COMMODITY_INDICATOR" to "நேரடி பிராந்திய மண்டி விலை",
            "CREDIT_ELIGIBILITY_TITLE" to "குரல் சரிபார்க்கப்பட்ட வணிகக் தகுதி",
            "CREDIT_SCORE_TITLE" to "குரல் வழி பணப்புழக்க மதிப்பெண்",
            "EXCELLENT" to "மிகவும் நன்று",
            "GOOD_TIER" to "நல்ல நிலை",
            "NEEDS_MORE_DATA" to "கூடுதல் தரவு தேவைப்படுகிறது",
            "CRYPTO_VOLUME" to "சரிபார்க்கப்பட்ட குரல் பரிவர்த்தனை மதிப்பு:",
            "PARTNER_INTEGRATION_TITLE" to "வங்கி / NBFC கூட்டாளர் ஒருங்கிணைப்பு",
            "APPLY_LOAN_BUTTON" to "பிணையில்லா கடனுக்கு விண்ணப்பிக்கவும்",
            "EXPLAINED_OUT_LOUD" to "குரல் உதவியாளர் விளக்கம்:",
            "DONE_BUTTON" to "சரி / முடிந்தது",
            "VOICE_TRANSLATION_TITLE" to "குரல் மொழிபெயர்ப்பு",
            "REGION_DEFAULT_BANNER" to "இருப்பிடத்திற்கு ஏற்ற அமைப்பு:",
            "ITEM" to "விவரம்",
            "CAT" to "பரிவர்த்தனை வகை",
            "QTY" to "அளவு",
            "RATE" to "விலை/அலகு",
            "TOTAL" to "மொத்த தொகை",
            "DEBT" to "கடன் பெற்றவர்"
        ),
        "Telugu" to mapOf(
            "APP_NAME" to "వాయిస్-ఓపిఎస్ ఏఐ",
            "SUBTITLE" to "చిన్న వ్యాపారాల వాయిస్ ఖాతా పుస్తకం",
            "AI_ACTIVE" to "ఏఐ యాక్టివ్‌గా ఉంది",
            "TOTAL_SALES" to "మొత్తం అమ్మకాలు",
            "UDHAAR_DUE" to "బాకీ ఉన్న అప్పు",
            "EXPENSES" to "మొత్తం ఖర్చులు",
            "MIC_TAP_PROMPT" to "మైక్ నొక్కి వ్యాపార వివరాలను మాట్లాడండి",
            "TAP_TO_SPEAK_LABEL" to "మాట్లాడటానికి నొక్కండి (తెలుగు/ఇంగ్లీష్)",
            "TRANSLATING" to "వాయిస్ అనువాదం అవుతోంది...",
            "DEMO_CHIPS_HEADER" to "డెమో చిప్స్: వాయిస్ అనుకరించడానికి నొక్కండి",
            "LEDGER_STREAM_TAB" to "📊 ఖాతా పుస్తకం",
            "MANDI_PRICES_TAB" to "🌾 తాజా మండి ధరలు",
            "VOICE_CREDIT_TAB" to "💳 వాయిస్ క్రెడిట్ స్కోరు",
            "LEDGER_EMPTY_TITLE" to "ఖాతా పుస్తకం ఖాళీగా ఉంది",
            "LEDGER_EMPTY_DESC" to "ఎలాంటి రికార్డులు లభించలేదు. మాట్లాడండి లేదా డెమో రికార్డులను లోడ్ చేయండి.",
            "LOAD_SAMPLE_BUTTON" to "డెమో డేటాను లోడ్ చేయి",
            "ACTIVE_RECORDS" to "యాక్టివ్ ఖాతా రికార్డులు వ్రాయబడ్డాయి",
            "CLEAR_ALL" to "అన్ని రికార్డులను తీసివేయి",
            "LIVE_COMMODITY_INDICATOR" to "ప్రాంతీయ పంటల తాజా ధరలు",
            "CREDIT_ELIGIBILITY_TITLE" to "అర్హత కలిగిన వాయిస్ వెరిఫైడ్ వ్యాపారం",
            "CREDIT_SCORE_TITLE" to "డిజిటల్ వాయిస్ లెడ్జర్ స్కోరు",
            "EXCELLENT" to "చాలా బాగుంది",
            "GOOD_TIER" to "మంచి స్థాయి",
            "NEEDS_MORE_DATA" to "మరింత సమాచారం కావాలి",
            "CRYPTO_VOLUME" to "వాయిస్ లెడ్జర్ లావాదేవీ మొత్తం:",
            "PARTNER_INTEGRATION_TITLE" to "బ్యాంక్ / NBFC భాగస్వామ్యం",
            "APPLY_LOAN_BUTTON" to "హామీ లేని లోన్ కొరకు దరఖాస్తు చేయండి",
            "EXPLAINED_OUT_LOUD" to "వాయిస్ అసిస్టెంట్ వివరణ:",
            "DONE_BUTTON" to "సరే / పూర్తయింది",
            "VOICE_TRANSLATION_TITLE" to "వాయిస్ అనువాద వివరాలు",
            "REGION_DEFAULT_BANNER" to "ప్రాంతీయ అనుకూల సెటప్:",
            "ITEM" to "వస్తువు",
            "CAT" to "లావాదేవీ రకం",
            "QTY" to "పరిమాణం",
            "RATE" to "యూనిట్ ధర",
            "TOTAL" to "మొత్తం ధర",
            "DEBT" to "అప్పు తీసుకున్న వ్యక్తి"
        ),
        "Bengali" to mapOf(
            "APP_NAME" to "ভয়েস-ওপিএস এআই",
            "SUBTITLE" to "ক্ষুদ্র ব্যবসায়ীদের ডিজিটাল খতিয়ান ওএস",
            "AI_ACTIVE" to "এআই সক্রিয় রয়েছে",
            "TOTAL_SALES" to "মোট বিক্রি",
            "UDHAAR_DUE" to "বকেয়া ধার",
            "EXPENSES" to "মোট খরচ",
            "MIC_TAP_PROMPT" to "মাইক টিপে ব্যবসার বিবরণ বলুন",
            "TAP_TO_SPEAK_LABEL" to "কথা বলতে স্পর্শ করুন (বাংলা/ইংরেজি)",
            "TRANSLATING" to "এআই আপনার কথা অনুবাদ করছে...",
            "DEMO_CHIPS_HEADER" to "ডেমো চিপস: কথা সিমুলেট করতে স্পর্শ করুন",
            "LEDGER_STREAM_TAB" to "📊 খতিয়ান প্রবাহ",
            "MANDI_PRICES_TAB" to "🌾 মণ্ডির দরদাম",
            "VOICE_CREDIT_TAB" to "💳 ভয়েস-ক্রেডিট যোগ্যতা",
            "LEDGER_EMPTY_TITLE" to "খতিয়ান খালি আছে",
            "LEDGER_EMPTY_DESC" to "কোনো রেকর্ড পাওয়া যায়নি। মাইকে কথা বলুন অথবা দ্রুত দেখার জন্য ডেমো রেকর্ড লোড করুন।",
            "LOAD_SAMPLE_BUTTON" to "ডেমো রেকর্ড লোড করুন",
            "ACTIVE_RECORDS" to "সক্রিয় রেকর্ড লেখা হয়েছে",
            "CLEAR_ALL" to "সব রেকর্ড মুছে ফেলুন",
            "LIVE_COMMODITY_INDICATOR" to "লাইভ আঞ্চলিক ফসলের মণ্ডি দর",
            "CREDIT_ELIGIBILITY_TITLE" to "ভয়েস-যাচাইকৃত ব্যবসায়িক যোগ্যতা প্রোফাইল",
            "CREDIT_SCORE_TITLE" to "ভয়েস খতিয়ান ক্রেডিট ক্যাশফ্লো স্কোর",
            "EXCELLENT" to "চমৎকার",
            "GOOD_TIER" to "ভালো স্তর",
            "NEEDS_MORE_DATA" to "আরো ডেটা প্রয়োজন",
            "CRYPTO_VOLUME" to "ভয়েস খতিয়ান মোট লেনদেন:",
            "PARTNER_INTEGRATION_TITLE" to "ব্যাঙ্ক / এনবিএফসি পার্টনার সংযোগ",
            "APPLY_LOAN_BUTTON" to "সহায়তাবিহীন ঋণের জন্য আবেদন করুন",
            "EXPLAINED_OUT_LOUD" to "আঞ্চলিক উচ্চারণে শোনানো হচ্ছে:",
            "DONE_BUTTON" to "ঠিক আছে / শেষ",
            "VOICE_TRANSLATION_TITLE" to "ভয়েস অনুবাদ ফলাফল",
            "REGION_DEFAULT_BANNER" to "অবস্থান-উপযোগী সেটআপ:",
            "ITEM" to "পণ্য বা বিবরণ",
            "CAT" to "লেনদেনের ধরন",
            "QTY" to "পরিমাণ",
            "RATE" to "মূল্য/একক",
            "TOTAL" to "মোট হিসাব",
            "DEBT" to "বকেয়াদার"
        ),
        "Kannada" to mapOf(
            "APP_NAME" to "ವಾಯ್ಸ್-ಓಪಿಎಸ್ ಏಐ",
            "SUBTITLE" to "ಸಣ್ಣ ವ್ಯವಹಾರಗಳ ಡಿಜಿಟಲ್ ಖಾತೆ ಪುಸ್ತಕ",
            "AI_ACTIVE" to "ಏಐ ಸಕ್ರಿಯವಾಗಿದೆ",
            "TOTAL_SALES" to "ಒಟ್ಟು ಮಾರಾಟ",
            "UDHAAR_DUE" to "ಬಾಕಿ ಇರುವ ಉದ್ರಿ",
            "EXPENSES" to "ಒಟ್ಟು ಖರ್ಚುಗಳು",
            "MIC_TAP_PROMPT" to "ಮೈಕ್ ಒತ್ತಿ ವ್ಯಾಪಾರದ ವಿವರಗಳನ್ನು ಮಾತನಾಡಿ",
            "TAP_TO_SPEAK_LABEL" to "ಮಾತನಾಡಲು ಒತ್ತಿ (ಕನ್ನಡ/ಇಂಗ್ಲಿಷ್)",
            "TRANSLATING" to "ಧ್ವನಿ ಅನುವಾದವಾಗುತ್ತಿದೆ...",
            "DEMO_CHIPS_HEADER" to "ಡೆಮೊ ಚಿಪ್ಸ್: ಧ್ವನಿ ಅನುಕರಿಸಲು ಒತ್ತಿ",
            "LEDGER_STREAM_TAB" to "📊 ಖಾತೆ ಪುಸ್ತಕ",
            "MANDI_PRICES_TAB" to "🌾 ತಾಜಾ ಮಂಡಿ ದರ",
            "VOICE_CREDIT_TAB" to "💳 ವಾಯ್ಸ್ ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್",
            "LEDGER_EMPTY_TITLE" to "ಖಾತೆ ಪುಸ್ತಕ ಖಾಲಿಯಾಗಿದೆ",
            "LEDGER_EMPTY_DESC" to "ಯಾವುದೇ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಮಾತನಾಡಲು ಮೈಕ್ ಬಳಸಿ ಅಥವಾ ಡೆಮೊ ದಾಖಲೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಿ.",
            "LOAD_SAMPLE_BUTTON" to "ಡೆಮೊ ಡೇಟಾ ಲೋಡ್ ಮಾಡಿ",
            "ACTIVE_RECORDS" to "ಸಕ್ರಿಯ ಖಾತೆ ದಾಖಲೆಗಳನ್ನು ಬರೆಯಲಾಗಿದೆ",
            "CLEAR_ALL" to "ಎಲ್ಲಾ ದಾಖಲೆಗಳನ್ನು ಅಳಿಸಿ",
            "LIVE_COMMODITY_INDICATOR" to "ಪ್ರಾದೇಶಿಕ ಬೆಳೆಗಳ ತಾಜಾ ಮಂಡಿ ದರ",
            "CREDIT_ELIGIBILITY_TITLE" to "ಧ್ವನಿ ಪರಿಶೀಲಿಸಿದ ವ್ಯಾಪಾರ ಅರ್ಹತೆ",
            "CREDIT_SCORE_TITLE" to "ಧ್ವನಿ ಲೆಡ್ಜರ್ ಕ್ರೆಡಿಟ್ ಕ್ಯಾಶ್ ಫ್ಲೋ ಸ್ಕೋರ್",
            "EXCELLENT" to "ಅತ್ಯುತ್ತಮ ಶ್ರೇಣಿ",
            "GOOD_TIER" to "ಉತ್ತಮ ಶ್ರೇಣಿ",
            "NEEDS_MORE_DATA" to "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ ಅಗತ್ಯವಿದೆ",
            "CRYPTO_VOLUME" to "ಸಹೀಕರಿಸಿದ ಧ್ವನಿ ಲೆಡ್ಜರ್ ಒಟ್ಟು ವಹಿವಾಟು:",
            "PARTNER_INTEGRATION_TITLE" to "ಬ್ಯಾಂಕ್ / NBFC ಪಾಲುದಾರಿಕೆ",
            "APPLY_LOAN_BUTTON" to "ಖಾತರಿ ಇಲ್ಲದ ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
            "EXPLAINED_OUT_LOUD" to "ಸ್ಥಳೀಯ ಉಚ್ಚಾರಣೆಯಲ್ಲಿ ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್ ವಿವರಣೆ:",
            "DONE_BUTTON" to "ಸರಿ / ಮುಗಿಯಿತು",
            "VOICE_TRANSLATION_TITLE" to "ಧ್ವನಿ ಅನುವಾದದ ವಿವರಗಳು",
            "REGION_DEFAULT_BANNER" to "ಸ್ಥಳೀಯ ಸೆಟಪ್ ವಿವರಗಳು:",
            "ITEM" to "ವಸ್ತು",
            "CAT" to "ವಹಿವಾಟಿನ ವಿಧ",
            "QTY" to "ಪ್ರಮಾಣ",
            "RATE" to "ಯೂನಿಟ್ ದರ",
            "TOTAL" to "ಒಟ್ಟು ದರ",
            "DEBT" to "ಸಾಲ ಪಡೆದ ವ್ಯಕ್ತಿ"
        ),
        "Marathi" to mapOf(
            "APP_NAME" to "व्हॉईस-ओपीएस एआय",
            "SUBTITLE" to "छोट्या व्यवसायांची डिजिटल वहीखाते",
            "AI_ACTIVE" to "एआय सक्रिय आहे",
            "TOTAL_SALES" to "एकूण विक्री",
            "UDHAAR_DUE" to "उधारी (बाकी)",
            "EXPENSES" to "एकूण खर्च",
            "MIC_TAP_PROMPT" to "माईक दाबा आणि व्यवसायाचे तपशील बोला",
            "TAP_TO_SPEAK_LABEL" to "बोलण्यासाठी दाबा (मराठी/इंग्रजी)",
            "TRANSLATING" to "आवाज अनुवादित होत आहे...",
            "DEMO_CHIPS_HEADER" to "डेमो बटणे: आवाज तपासण्यासाठी दाबा",
            "LEDGER_STREAM_TAB" to "📊 वहीखाते इतिहास",
            "MANDI_PRICES_TAB" to "🌾 ताजे मंडी भाव",
            "VOICE_CREDIT_TAB" to "💳 व्हॉईस क्रेडिट स्कोअर",
            "LEDGER_EMPTY_TITLE" to "वहीखाते रिकामे आहे",
            "LEDGER_EMPTY_DESC" to "कोणतेही रेकॉर्ड आढळले नाही. माईक वापरून बोला किंवा चाचणीसाठी डेमो रेकॉर्ड लोड करा.",
            "LOAD_SAMPLE_BUTTON" to "डेमो माहिती लोड करा",
            "ACTIVE_RECORDS" to "सक्रिय व्यापार रेकॉर्ड लिहिण्यात आले",
            "CLEAR_ALL" to "सर्व रेकॉर्ड साफ करा",
            "LIVE_COMMODITY_INDICATOR" to "ताज्या प्रादेशिक कृषी उत्पन्न बाजार दर",
            "CREDIT_ELIGIBILITY_TITLE" to "आवाज-सत्यापित व्यापार कर्ज पात्रता",
            "CREDIT_SCORE_TITLE" to "व्हॉईस लेजर क्रेडिट कॅशफ्लो स्कोअर",
            "EXCELLENT" to "उत्कृष्ट रेटिंग",
            "GOOD_TIER" to "चांगला स्तर",
            "NEEDS_MORE_DATA" to "अधिक माहितीची आवश्यकता आहे",
            "CRYPTO_VOLUME" to "सत्यापित व्हॉईस लेजर एकूण व्यवहार:",
            "PARTNER_INTEGRATION_TITLE" to "सहकारी बँक व ग्रामीण फायनान्स भागीदारी",
            "APPLY_LOAN_BUTTON" to "विना-तारण कर्जासाठी अर्ज करा",
            "EXPLAINED_OUT_LOUD" to "स्थानिक भाषेतील स्पष्टीकरण:",
            "DONE_BUTTON" to "ठाक आहे / पूर्ण झाले",
            "VOICE_TRANSLATION_TITLE" to "व्हॉईस भाषांतर परिणाम",
            "REGION_DEFAULT_BANNER" to "स्थान-अनुकूलित डीफॉल्ट सेटअप:",
            "ITEM" to "उत्पादनाचे नाव",
            "CAT" to "व्यवहार श्रेणी",
            "QTY" to "प्रमाण तपशील",
            "RATE" to "प्रति युनिट दर",
            "TOTAL" to "एकूण गणना केलेली रक्कम",
            "DEBT" to "उधारी घेणारा"
        )
    )

    fun translate(language: String, key: String): String {
        val langMap = translations[language] ?: translations["English"]!!
        return langMap[key] ?: translations["English"]!![key] ?: key
    }

    val demoChipsByLanguage = mapOf(
        "English" to listOf(
            DemoChipData("Sale: 40kg Potato @ ₹30", "Today I sold 40 kg potatoes for 30 rupees per kg"),
            DemoChipData("Lend: Ramesh ₹500", "Lent Ramesh 500 rupees udhaar"),
            DemoChipData("Mandi: Onion Price?", "What is the mandi price of onion today?"),
            DemoChipData("Exp: Petrol ₹450", "Fuel expense for transport was 450 rupees"),
            DemoChipData("Check Credit Status", "Check my voice ledger credit eligibility score")
        ),
        "Hindi" to listOf(
            DemoChipData("बिक्री: 40 किलो आलू @ ₹30", "आज चालीस किलो आलू बेचा तीस रुपये किलो के हिसाब से"),
            DemoChipData("उधार: रमेश ₹500", "रमेश को पांच सौ रुपये उधार दिए लिख लो"),
            DemoChipData("मंडी: प्याज का भाव?", "आज प्याज का मंडी भाव क्या चल रहा है"),
            DemoChipData("खर्च: पेट्रोल ₹450", "मंडी जाने का डीजल का खर्च साढ़े चार सौ रुपये"),
            DemoChipData("क्रेडिट स्थिति जांचें", "मेरी वॉयस बहीखाता लोन और क्रेडिट स्थिति क्या है")
        ),
        "Hinglish" to listOf(
            DemoChipData("Sale: 40kg Aloo @ ₹30", "Aaj 40 kg aloo beche, 30 rupaye kilo"),
            DemoChipData("Lend: Ramesh ₹500", "Ramesh ko 500 rupaye udhaar diye"),
            DemoChipData("Mandi: Onion Price?", "Pyaj ka mandi bhav kya chal raha hai"),
            DemoChipData("Exp: Petrol ₹450", "Mandi jane ka diesel ka kharach 450 rupaye"),
            DemoChipData("Check Credit Status", "Mera voice ledger loan limit details check karo")
        ),
        "Tamil" to listOf(
            DemoChipData("விற்பனை: 40கி உருளை @ ₹30", "இன்று 40 கிலோ உருளைக்கிழங்கு கிலோ 30 ரூபாய்க்கு விற்றேன்"),
            DemoChipData("கடன்: ரமேஷ் ₹500", "ரமேஷுக்கு 500 ரூபாய் கடன் கொடுத்துள்ளேன்"),
            DemoChipData("மண்டி: வெங்காய விலை?", "இன்று வெங்காயம் மண்டி விலை என்ன"),
            DemoChipData("செலவு: பெட்ரோல் ₹450", "வண்டிக்கு பெட்ரோல் செலவு 450 ரூபாய்"),
            DemoChipData("கடன் தகுதியைச் சரிபார்", "எனது குரல் வழி கடன் தகுதி மதிப்பெண் என்ன")
        ),
        "Telugu" to listOf(
            DemoChipData("అమ్మకం: 40కి బంగాళాదుంప @ ₹30", "ఈరోజు 40 కిలోల బంగాళాదుంపలు కిలో 30 రూపాయలకు విక్రయించాను"),
            DemoChipData("అప్పు: రమేష్ ₹500", "రమేశ్ కి 500 రూపాయలు అప్పుగా ఇచ్చాను"),
            DemoChipData("మండి: ఉల్లిపాయ ధర?", "ఈరోజు ఉల్లిపాయ మండి ధర ఎంత ఉంది"),
            DemoChipData("ఖర్చు: పెట్రోల్ ₹450", "మండికి వెళ్లడానికి డీజిల్ ఖర్చు 450 రూపాయలు"),
            DemoChipData("క్రెడిట్ స్టేటస్ చెక్", "నా వాయిస్ లెడ్জার లోన్ క్రెడిట్ స్కోర్ ఎంత")
        ),
        "Bengali" to listOf(
            DemoChipData("বিক্রি: ৪০ কেজি আলু @ ₹৩০", "আজ ৪০ কেজি আলু বিক্রি করেছি ৩০ টাকা কেজি দরে"),
            DemoChipData("ধার: রমেশ ₹৫০০", "রমেশকে ৫০০ টাকা ধার দিয়েছি খাতায় লিখে রাখুন"),
            DemoChipData("মণ্ডি: পেঁয়াজের দাম?", "আজ পেঁয়াজের মণ্ডি দর কত চলছে বলুন তো"),
            DemoChipData("খরচ: পেট্রোল ₹৪৫০", "মণ্ডি যাওয়ার জন্য ডিজেল খরচ হয়েছে ৪৫০ টাকা"),
            DemoChipData("ক্রেডিট স্কয়ার দেখুন", "আমার ব্যাঙ্ক লোন এবং ক্রেডিট স্কোরের স্থিতি পরীক্ষা করুন")
        ),
        "Kannada" to listOf(
            DemoChipData("ಮಾರಾಟ: 40ಕೆಜಿ ಆಲೂಗಡ್ಡೆ @ ₹30", "ಇಂದು ನಾನು 40 ಕೆಜಿ ಆಲೂಗಡ್ಡೆಯನ್ನು ಕಿಲೋಗೆ 30 ರೂಪಾಯಿಯಂತೆ ಮಾರಾಟ ಮಾಡಿದೆನು"),
            DemoChipData("ಉದ್ರಿ: ರಮೇಶ್ ₹500", "ರಮೇಶನಿಗೆ 500 ರೂಪಾಯಿ ಉದ್ರಿ ನೀಡಿದ್ದೇನೆ ಬರೆದುಕೋ"),
            DemoChipData("ಮಂಡಿ: ಈರುಳ್ಳಿ ದರ?", "ಇಂದು ಈರುಳ್ಳಿ ಮಂಡಿ ದರ ಏನು ನಡೀತಿದೆ ತಿಳಿಸು"),
            DemoChipData("ಖರ್ಚು: ಪೆಟ್ರೋಲ್ ₹450", "ಮಂಡಿಗೆ ಹೋಗಲು ಡೀಸೆಲ್ ಖರ್ಚು 450 ರೂಪಾಯಿ ಆಯಿತು"),
            DemoChipData("ಕ್ರೆಡಿಟ್ ಅರ್ಹತೆ ಚೆಕ್", "ನನ್ನ ಧ್ವನಿ ಲೆಡ್ಜರ್ ಸಾಲ ಮತ್ತು ಕ್ರೆಡಿಟ್ ಅರ್ಹತೆ ಏನು ಎಂದು ನೋಡು")
        ),
        "Marathi" to listOf(
            DemoChipData("विक्री: 40 किलो बटाटा @ ₹30", "आज मी 40 किलो बटाटे प्रति किलो 30 रुपये दराने विकले"),
            DemoChipData("उधारी: रमेश ₹500", "रमेशला 500 रुपये उधार दिले आहेत लिहून ठेवा"),
            DemoChipData("मंडी: कांदा भाव?", "आज कांद्याचा मंडी भाव काय चालू आहे सांगा"),
            DemoChipData("खर्च: पेट्रोल ₹450", "बाजारपेठेत जाण्यासाठी डिझेलचा खर्च साडेचारशे रुपये झाला"),
            DemoChipData("कर्ज पात्रता तपासा", "माझा व्हॉईस लेजर क्रेडिट लोन स्कोअर काय आहे")
        )
    )
}
